"""add_unique_constraint_entry_subject_session_rep

Revision ID: 3f6ad6c3c98f
Revises: bfe7a296746a
Create Date: 2026-02-28 15:16:15.814062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6ad6c3c98f'
down_revision = 'bfe7a296746a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_entries', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_entry_subject_session_rep', ['subject_id', 'session_no', 'repetition'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_entries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_entry_subject_session_rep', type_='unique')

    # ### end Alembic commands ###
