"""add last_login and last_login_ip to users

Revision ID: 4e874540c68b
Revises: 2cb60a1efd73
Create Date: 2026-05-03 22:41:16.713902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e874540c68b'
down_revision = '2cb60a1efd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=45), nullable=True))

    with op.batch_alter_table('users_vectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_vectors_data_type'))
        batch_op.drop_column('data_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_vectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_users_vectors_data_type'), ['data_type'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
