"""add_is_successful_to_users_vectors

Revision ID: 7d05f4d357b0
Revises: c7f1b0b6a9d1
Create Date: 2026-03-06 15:18:23.215038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect as sa_inspect


# revision identifiers, used by Alembic.
revision = '7d05f4d357b0'
down_revision = 'c7f1b0b6a9d1'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if 'users_vectors' not in sa_inspect(bind).get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_vectors', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_vectors_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    if 'users_vectors' not in sa_inspect(bind).get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_vectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_vectors_timestamp'))
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
