"""Initial migration with User, KeystrokeVector, LoginAttempt models

Revision ID: c63a68a64ec8
Revises:
Create Date: 2025-12-24 03:11:14.875839

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c63a68a64ec8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
        batch_op.alter_column(
            "username",
            existing_type=sa.TEXT(),
            type_=sa.String(length=80),
            nullable=False,
        )
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.TEXT(),
            type_=sa.String(length=255),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "plain_password",
            existing_type=sa.TEXT(),
            type_=sa.String(length=255),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "plain_password",
            existing_type=sa.String(length=255),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=255),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "username",
            existing_type=sa.String(length=80),
            type_=sa.TEXT(),
            nullable=True,
        )
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
